# Generated by Django 3.1.7 on 2021-03-27 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='текст')),
                ('image', models.ImageField(upload_to='images/items/%Y/%m/%d', verbose_name='изображение')),
                ('content', models.TextField(blank=True, null=True, verbose_name='дополнительный контент')),
                ('url', models.URLField(blank=True, verbose_name='ссылка')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='online: ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания: ')),
                ('is_active', models.BooleanField(default=False, verbose_name='принято')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('comment', models.TextField(max_length=120, verbose_name='комментарий')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания: ')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.board', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
