# Generated by Django 3.1.7 on 2021-03-20 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания: '),
        ),
        migrations.AddField(
            model_name='board',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='online: '),
            preserve_default=False,
        ),
    ]
