# Generated by Django 3.1.7 on 2021-03-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210320_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(null=True, verbose_name='дополнительный контент'),
        ),
    ]
