# Generated by Django 3.1.7 on 2021-03-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210329_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('active', '-created'), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='is_active',
            new_name='active',
        ),
    ]
