# Generated by Django 3.1.7 on 2021-03-30 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0006_auto_20210329_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='ad',
            new_name='post',
        ),
    ]
