# Generated by Django 3.1.7 on 2021-03-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210330_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
